[package]
name = "bevy-pbr-rust"
version = "0.2.0"
edition = "2021"

[lib]
crate_type = ["dylib", "rlib"]

[dependencies]
bitflags = "1.3.2"
spirv-std = { version = "0.5.0", features = ["glam"] }
permutate-macro = { git = "https://github.com/Bevy-Rust-GPU/permutate-macro", tag = "v0.4.0" }
rust-gpu-bridge = { git = "https://github.com/Bevy-Rust-GPU/rust-gpu-bridge", tag = "v0.2.0", features = ["spirv-std"] }
