[package]
name = "bevy-pbr-rust"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
permutate-macro = { git = "https://github.com/Bevy-Rust-GPU/permutate-macro" }
rust-gpu-bridge = { git = "https://github.com/Bevy-Rust-GPU/rust-gpu-bridge" }

[dependencies]
bitflags = "1.3.2"
spirv-std = "0.5.0"
permutate-macro = "0.1.0"
rust-gpu-bridge = { version = "0.1.0", default-features = false, features = ["spirv-std"] }
