[build]
target = "spirv-unknown-spv1.5"
rustflags = [
    "-Zcodegen-backend=/mnt/projects/personal/rust/Projects/bevy-rust-gpu-project/rust-gpu/target/release/librustc_codegen_spirv.so",
    "-Zbinary-dep-depinfo",
    "-Csymbol-mangling-version=v0",
    "-Zcrate-attr=feature(register_tool)",
    "-Zcrate-attr=register_tool(rust_gpu)"
]

[unstable]
build-std=["core"]
build-std-features=["compiler-builtins-mem"]
