name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: 'shader'
    - uses: actions/checkout@v3
      with:
        repository: 'EmbarkStudios/rust-gpu'
        path: 'rust-gpu'
    - name: List working directory
      run: ls
    - name: List workspace directory
      run: ls ${{ github.workspace }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
