name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: 'shader'
    - uses: actions/checkout@v3
      with:
        repository: 'EmbarkStudios/rust-gpu'
        path: 'rust-gpu'
    - name: Build rust-gpu
      run: |
        cd rust-gpu
        cargo build --release --verbose
    - name: Build shader
      run: |
        cd shader
        cargo build --verbose
    - name: Run tests
      run: |
        cd shader
        cargo test --verbose
